#!/bin/bash
PROGRAM=/usr/sbin/athcool
NAME="Athcool"
RUNLEVEL=3
. /etc/init.d/smgl_init

start() {
	echo "Starting athcool..."
	${PROGRAM} on
}

stop() {
	echo "Stoping athcool..."
	${PROGRAM} off
}

restart() {
	stop 	&&
	sleep 1 &&
	start
}

