if [ "$FAAD_CVS" = "y" ]; then
	OPTS="$OPTS --with-drm"
fi	                            &&
OPTS="$OPTS --with-mp4v2"       &&
if [ "$XMMS" != "y" ]; then
  OPTS="$OPTS --without-xmms"
fi  &&
default_build
