for SYLPHEED_PLUGIN in $SYLPHEED_CLAWS_EXTRA_PLUGINS
do
 message "${MESSAGE_COLOR}claws-mail-extra-plugin $SYLPHEED_PLUGIN is being built...${DEFAULT_COLOR}"
 cd $SOURCE_DIRECTORY/$SYLPHEED_PLUGIN*
 default_build
done
