#!/bin/sh
#
# SMGL-script-version=20030224
# SMGL-START:1 2 3 4 5:S35
# SMGL-STOP:0 6:K50

. /etc/sysconfig/slapd

PROGRAM=/usr/libexec/slapd

RUNLEVEL=3
NEEDS="+remote_fs"

. /etc/init.d/smgl_init

start() {
	echo "Starting slapd...."
	# this works, starts both of them nicely
	$PROGRAM -h "$SLAPD_URL"
	evaluate_retval
}
