#!/bin/bash

. /etc/sysconfig/xl2tpd

PROGRAM=/usr/sbin/xl2tpd
PIDFILE="/var/run/xl2tpd.pid"
ARGS="$XL2TPD_ARGS"
RUNLEVEL=3
NEEDS="+network +local_fs"

. /etc/init.d/smgl_init

start() {
  [ -d /var/run/xl2tpd ] || mkdir /var/run/xl2tpd

  _start
}
