#!/bin/bash

. /etc/sysconfig/burp

if [[ $STATIC == "yes" ]] && [[ -x /usr/sbin/static-burp ]]; then
  PROGRAM=/usr/sbin/static-burp
else
  PROGRAM=/usr/sbin/burp
fi

PIDFILE=/var/run/burp/server.pid
ARGS="-c /etc/burp/burp-server.conf $BURP_ARGS"
RUNLEVEL=3
NEEDS="+network"

. /etc/init.d/smgl_init

stop() {
  _stop
  rm -f "$PIDFILE"
}
