#!/bin/bash

PROGRAM=/bin/false
RUNLEVEL=1
NEEDS="+local_fs"

. /etc/init.d/smgl_init
. /etc/sysconfig/init

MAX_LEVEL=$DEFAULT_RUNLEVEL

case "$MAX_LEVEL" in
  1)
        SPLASHY_PROGRESS=100
        ;;
  2)
        SPLASHY_PROGRESS=50
        ;;
  3)
        SPLASHY_PROGRESS=33
        ;;
  4)
        SPLASHY_PROGRESS=25
        ;;
  5)
        SPLASHY_PROGRESS=20
        ;;
  *)
        echo "Unknown default runlevel"
        exit 1
esac

start()
{
  /usr/sbin/splashy_update "progress $SPLASHY_PROGRESS"
}

stop()
{
  true
}

restart()
{
  true
}
