--- Makefile~	2007-01-02 16:58:41.000000000 +0200
+++ Makefile	2007-01-07 01:39:26.000000000 +0200
@@ -285,11 +285,6 @@
 	@extras="$(EXTRAS)"; for target in $$extras; do \
 		$(MAKE) -C $$target $@ || exit 1; \
 	done;
-ifndef DESTDIR
-	- killall udevd
-	- rm -rf /dev/.udev
-	- $(sbindir)/udevd --daemon
-endif
 .PHONY: install-bin
 
 uninstall-bin:
