#!/bin/bash

PROGRAM=/usr/sbin/squid
RUNLEVEL=3
NEEDS="+network +remote_fs"

. /etc/init.d/smgl_init

start()
{
  echo "Building squid swap directories..."
  /usr/sbin/squid -z -F > /dev/null 2>&1
  evaluate_retval
  echo "Starting squid..."
  loadproc /usr/sbin/squid
}

reload()
{
  echo "Reloading squid..."
  /usr/sbin/squid -k reconfigure > /dev/null 2>&1
  evaluate_retval
}

stop()
{
  echo "Stopping squid..."
  /usr/sbin/squid -k shutdown > /dev/null 2>&1
  evaluate_retval
}

restart()
{
  stop
  # Squid has a 30s connection timeout when shutting down
  sleep 35
  start
}
