#!/bin/bash

PIDFILE=/var/run/uwsgi-emperor.pid
LOGFILE=/var/log/uwsgi-emperor.log
VASSALS_DIR=/etc/uwsgi
PROGRAM=/usr/bin/uwsgi
ARGS="--emperor ${VASSALS_DIR} --pidfile ${PIDFILE} --daemonize ${LOGFILE} --die-on-term"
RUNLEVEL=3
NEEDS="+network +remote_fs"

. /etc/init.d/smgl_init
