#!/bin/bash

PROGRAM=/bin/false
RUNLEVEL=S
NEEDS="+local_fs"

. /etc/init.d/smgl_init

start()
{
  /sbin/uptimed  -b
}

stop()
{
  exit 0
}

restart()       { exit 3; }
reload()        { exit 3; }
force_reload()  { exit 3; }
status()        { exit 3; }

usage()
{
  echo "Usage: $0 {start|stop}"
  echo "Warning: This script should only be run once after boot!"
}
