echo  "gcc ${CFLAGS} -include /usr/include/errno.h"  >conf-cc    &&
echo  "gcc ${LDFLAGS}"                               >conf-ld    &&
echo  "/usr"                                         >conf-home  &&
make
