#!/bin/bash
#
# SMGL init script for the update server of codafs
#

PROGRAM=/bin/false
RUNLEVEL=3
NEEDS="+remote_fs +network"
SCMFILE=/vice/db/scm

. /etc/init.d/smgl_init

start()
{
    required_executable /usr/sbin/rpc2portmap
    required_executable /usr/sbin/updatesrv
    required_executable /usr/sbin/updateclnt
    
    echo   "Starting Coda update server"
    loadproc /usr/sbin/rpc2portmap
    loadproc /usr/sbin/updatesrv
    loadproc /usr/sbin/updateclnt -h `cat $SCMFILE`
}

stop()
{
    echo   "Stopping Coda update server"
    killproc /usr/sbin/updateclnt
    killproc /usr/sbin/updatesrv
    killproc /usr/sbin/rpc2portmap
}
