 pfx="$INSTALL_ROOT"/usr
conf="$INSTALL_ROOT"/etc
slib="$INSTALL_ROOT"/lib
 lib="$pfx"/lib/musl
 inc="$pfx"/include/musl
./configure \
    --prefix="$pfx"        \
    --sysconfdir="$conf"   \
    --syslibdir="$slib"    \
    --libdir="$lib"        \
    --includedir="$inc"    \
    $OPTS
