#!/bin/bash

PROGRAM=/usr/bin/adb
ARGS=""
RUNLEVEL=3
PIDFILE=/var/run/adb.pid

. /etc/init.d/smgl_init

start() {
  ${PROGRAM} start-server
  ${PROGRAM} devices
}

stop() {
  ${PROGRAM} kill-server
}
