create_account uucp                                            &&

sedit 's:/usr/spool/uucp/Debug:/var/log/uucp/Debug:'  policy.h &&
sedit 's:/usr/spool/uucp/Log:/var/log/uucp/Log:'      policy.h &&
sedit 's:/usr/spool/uucp/Stats:/var/log/uucp/Stats:'  policy.h &&
sedit 's:/usr/spool/uucp:/var/spool/uucp:'            policy.h &&

default_build
