#!/bin/bash

#
# /etc/sysconfig/exim needs to be sourced before ARGS
#
. /etc/sysconfig/exim

PROGRAM=/usr/sbin/exim
ARGS="-bd -q${QUEUE_DELAY}"
PIDFILE="/var/run/exim.pid"
RUNLEVEL=3
NEEDS="+network"

. /etc/init.d/smgl_init
