#./configure  --build=$BUILD        \
#             --prefix=/usr         \
#             --sysconfdir=/etc     \
#             --localstatedir=/var  \
#             $OPTS                 &&
#make
default_build
