--- Makefile.old	2008-09-07 15:50:03.000000000 +0200
+++ Makefile	2008-09-07 15:52:22.000000000 +0200
@@ -17,7 +17,7 @@
 CFLAGS		= -g -Wall -O2 -I $(KERNELHEADER)
 
 DESTDIR		=
-PREFIX		= /usr/local
+PREFIX		= ${INSTALL_ROOT}/usr
 
 INSDIR		= $(PREFIX)/sbin
 MANDIR		= $(PREFIX)/man/man8
@@ -50,13 +50,13 @@
 	$(INS) -m 644 $(MANPAGE) $(DESTDIR)$(MANDIR)
 	gzip -9f $(DESTDIR)$(MANDIR)/$(MANPAGE)
 
-	$(INS) -m 755 $(RCFILE) $(DESTDIR)$(RCFILETO)/$(RCFILEFINAL)
+#	$(INS) -m 755 $(RCFILE) $(DESTDIR)$(RCFILETO)/$(RCFILEFINAL)
 
-ifndef DESTDIR
-		chkconfig --add $(RCFILEFINAL)
-else
-		echo "MAKE: Skipping chkconfig operation (rpm build?)"
-endif
+#ifndef DESTDIR
+#		chkconfig --add $(RCFILEFINAL)
+#else
+#		echo "MAKE: Skipping chkconfig operation (rpm build?)"
+#endif
 
 device:
 	mkdir -p $(DESTDIR)/dev/cpu
