OPTS+=' smack=false tests=unsafe split-usr=true' &&
OPTS+=' split-bin=true' &&
OPTS+=' rootlibdir=/lib' &&
OPTS+=' default-hierarchy=hybrid' &&
OPTS+=' cgroup-controller=none' &&
OPTS+=' nobody-group=nogroup' &&
default_build

