.Dd October 29, 2015
.Dt LHA 1
.Os
.Sh NAME
.Nm lha
.Nd lzh un-archiver
.Sh SYNOPSIS
.Nm
.Op Fl axelvudmcp
.Op Fl qvnfodizg012
.Op Fl w Ns = Ns Ar dir
.Ar archive_file
.Op Ar files
.Sh DESCRIPTION
The
.Nm
program displays or extracts the contents of an LZH archive.
For a list of commands, refer to the executable itself: running
.Nm
without any parameter displays the list of valid commands and modifiers.
.Sh COMMANDS
.Bl -tag -width Ds
.It Fl a
Add files to the archive, replacing existing entries
.It Fl l , Fl v
List the archive contents;
.Fl v
gives a verbose listing
.It Fl u
Update newer files in the archive
.It Fl d
Delete files from the archive
.It Fl m
Move files into the archive
.It Fl c
Reconstruct a new archive
.It Fl p
Print files from the archive to standard output
.It Fl t
Test the file CRC in the archive
.El
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl q
Quiet
.It Fl v
Verbose
.It Fl n
Do not execute
.It Fl f
Force, overwriting when extracting
.It Fl t
Files are TEXT-files
.It Fl o
Use the LHarc compatible compression method
.It Fl w Ar dir
Extract into
.Ar dir
.It Fl d
Delete files afterwards
.It Fl i
Ignore the directory path
.It Fl z
Files not compress
.It Fl g
Generic format, for compatibility
.It Fl 0 , Fl 1 , Fl 2
Header level
.It Fl e
TEXT code convert from/to EUC
.El
