OPTS="--boost-inc-dir=${INSTALL_ROOT}/usr/include/boost \
      --taglib-inc-dir=${INSTALL_ROOT}/usr/include/taglib \
      --boost-python-libname=boost_python \
      ${OPTS}" &&

./configure.py ${OPTS} &&
make
